name: user_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  firebase_core: ^2.10.0
  firebase_auth: ^4.4.2
  http: ^1.1.0
  get: 4.6.5
  flutter: 
    sdk: flutter
  pinput: ^3.0.1
  flutter_onboarding_slider: ^1.0.9
  country_picker: ^2.0.20
  country_code_picker: ^3.0.0
  cloud_firestore: ^4.9.0

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

